Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.vm.synced_folder ".", "/vagrant",
    type: "virtualbox"

    ### Nginx VM ###

    config.vm.define "ngx01" do |ngx01|
        ngx01.vm.box = "generic/ubuntu2204"
        ngx01.vm.hostname = "ngx01"
        ngx01.vm.network "private_network", ip: "192.168.56.11"
        ngx01.vm.provision "shell", path: "scripts/ngx01.sh"
    end

    ### Tomcat VM ###
    config.vm.define "tc01" do |tc01|
        tc01.vm.box = "generic/rocky9"
        tc01.vm.hostname = "tc01"
        tc01.vm.network "private_network", ip: "192.168.56.12"
        tc01.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
        end
        tc01.vm.synced_folder "../target", "/target", create: true
        tc01.vm.provision "shell", path: "scripts/tc01.sh"
    end

    ### rabbitmq VM ###
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "generic/rocky9"
        rmq01.vm.hostname = "rmq01"
        rmq01.vm.network "private_network", ip: "192.168.56.16"
        rmq01.vm.provision "shell", path: "scripts/rmq01.sh"
    end

    ### memcached VM ###
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "generic/rocky9"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", ip: "192.168.56.14"
        mc01.vm.provision "shell", path:"scripts/mc01.sh"
    end

    ### db VM ###
    config.vm.define "db01" do |db01|
        db01.vm.box = "generic/rocky9"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.15"
        db01.vm.provision "shell", path: "scripts/db01.sh"
    end
end

