#JDBC Configutation for Database Connection
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://vprofile-db.c8ns8cu42mka.us-east-1.rds.amazonaws.com:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
jdbc.username=admin
jdbc.password=AWSdatabase123

#Memcached Configuration For Active and StandBy Host
#For Active Host
memcached.active.host=vprofile-cache-cluster.6scenx.0001.cfg.use1.cache.amazonaws.com
memcached.active.port=11211
#For StandBy Host
memcached.standBy.host=127.0.0.2
memcached.standBy.port=11211

#RabbitMq Configuration
rabbitmq.address=rmq01
rabbitmq.port=5672
rabbitmq.username=test
rabbitmq.password=test

rabbitmq.address=vprofile-mq
rabbitmq.port=5671
rabbitmq.username=test
rabbitmq.password=AWSrabbitmq123


